### ISSUE TITLE
Should document how to use this from requirements.txt, setup.py etc

### ISSUE THREAD

**Issue by phlummox** [phlummox/pyinfra-dokku#5]
in a requirements.txt or requirements.in file:

```
pyinfra-dokku @ git+https://github.com/phlummox/pyinfra-dokku@v0.1.1
```

in a setup.py file:

```python
import os
from setuptools import setup, find_packages

setup(
  # ...
  install_requires = ['pyinfra-dokku @ git+https://github.com/phlummox/pyinfra-dokku@v0.1.1',
                      # ... etc etc
                     ],
```

in pyproject.toml:

```toml;
[project]
dependencies = [
    'pyinfra-dokku @ git+https://github.com/phlummox/pyinfra-dokku@v0.1.1',
]
```
